### ISSUE TITLE
-O3 is passed even for CMAKE_BUILD_TYPE=Debug

### ISSUE THREAD

**Issue by danlipsa** [SENSEI-insitu/SENSEI#139]
Both -g and -O3 are passed for debug build. That makes debugging difficult.

**Comment by danlipsa** [comment]
@burlen Any ideas here? Thanks!

**Comment by burlen** [comment]
When configuring SENSEI for Debug build -O3 is not present. 

However, note that if you first configure SENSEI for a Release build, then later try to change to a Debug build, you will need to start fresh or modify your CMakeCache.txt manually since CMake will not reconfigure cached variables including CXX_FLAGS. This is not a bug in SENSEI but rather a feature of CMake.

**Comment by burlen** [comment]
After looking at our code, it may be the case that we could move the optimization related flags from CXX_FLAGS to CXX_FLAGS_RELEASE making the reconfigure unnecessary.
