### ISSUE TITLE
Bug: Unconditional injection of CXX Flags

### ISSUE THREAD

**Issue by ax3l** [SENSEI-insitu/SENSEI#15]
While debugging AMReX and WarpX CMake builds, I realized that SENSEI does unconditionally inject C++ flags such as std, optimization level, warning flags and even std library choices into downstream code:
https://github.com/SENSEI-insitu/SENSEI/blob/73873211eadc290991dcd62a5edddc45dc09d2bb/CMake/build.cmake#L18-L26

This causes problems when compiling complex applications downstream, e.g., if we choose another C++ standard, need other C++ flags, couple further third party libraries besides SENSEI as dependencies, control platform flags and rely on compiler defaults, as is common for CMake logic in general (only add flags if needed for a requirement).

There are simple ways to fix this in SENSEI:
- For  C++ standard requirements, please use `target_compile_features(... PRIVATE cxx_std_14)`.
- For fPIC, please us the target property `POSITION_INDEPENDENT_CODE` on the SENSEI target, etc.
- use the CMake build options for optimizaitons instead of adding `-O<N>` manually
- only add your warning flags such as `-Wall -Wextra` as `PRIVATE` flags or set them only in CI (e.g., via `export CXXFLAGS`)
- do not inject `-march=native -mtune=native` unconditionally, this is a package managers or environment job and breaks cross-compiles
- don't change the C++ stdlib implementation
- etc.

I saw this using the `ryankrattiger/sensei:fedora33-vtk-mpi-20210616` docker image and we pick up SENSEI via `find_package` config CMake files, which carried the above noisy flags in CXXFLAGS.

X-ref: https://github.com/AMReX-Codes/amrex/pull/2115/files#r691544975

**Comment by burlen** [comment]
to summarize: if this is an issue set `CMAKE_CXX_FLAGS` to something (can be an empty string) and our cmake code will not modify them.

**Comment by burlen** [comment]
It's a good suggestion here and I took a stab at trying the "cmake way" as suggested above. 

Still having some issue with CMake not passing flags correctly. The problem is worse when CUDA in play. Two notable instances. Issue 1: -fvisibility=hidden is not passed to the CUDA linker which leads to nasty run time crash when mixing shared and static libraries compiled and linked with nvcc (does not happen with all shared libs). Issue 2: OpenMP flags are not passed to host compiler when nvcc is used, and OpenMP pragmas are ignored. 

Both those cases have to be manually injected, and for that reason we're unfortunately still forced to set compiler flags ourselves.
